baseURL = 'https://morgue.keinmal.top/'
locale = 'zh-cn'
title = 'Morgue'
contentDir = 'morgue'

[taxonomies]
tag = 'tags'
category = 'categories'
series = 'series'
topic = "topics"
genre = "genres"
status = "status"
