name: Sync from content to site

on:
  push:
    branches:
      - morgue

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout blogs repository
        uses: actions/checkout@v5
        with:
          repository: hiraethecho/blogs
          ref: morgue
          path: blogs
      - name: commit
        run: |
          cd blogs
          git log -1 --pretty=%B > ~/commit
      - name: Checkout note repository
        uses: actions/checkout@v5
        with:
          repository: hiraethecho/morgue
          ssh-key: ${{ secrets.OB_MORGUE_PRI }}
          path: morgue
      - name: push
        run: |
          rsync -av --delete --exclude='.git' --exclude='.obsidian' blogs/ morgue/content/
          cd morgue
          git config --global user.name "blogs"
          git config --global user.email "wyz2016zxc@126.com"
          git add .
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes detected, skipping push."
          else
            git commit -m "Sync content $(cat ~/commit)"
            git push
          fi
